
script:
- echo "This is the TRAVIS build script for the e0 Testing Software"
- echo "-----------------------------------------------------------"
- FLASK_APP=todo_app/app
- FLASK_ENV=development

# Now we need to run the unit tests to see if this build is good (after building the docker image)
- docker build --target test --tag my-test-image .
- docker run -p 5000:5000 my-test-image

# Next, if all is good, we need to build and run other tests to confirm software
- docker build --target test --tag todoapptest .
- docker run -p 5000:5000 todoapptest

# If all is good, prepare production image

- docker build --target production -f Dockerfile --tag $DOCKERHUB_USERNAME/e0testingapp:prod
  .
# - echo $dockerhub_password | docker login --username $DOCKERHUB_USERNAME --password-stdin
- echo "Now for the push"
- echo "----------------"
- docker push britboy4321/e0testingapp   

#  Continous deployment

- docker pull britboy4321/e0testingapp:prod      #  Ensure that we have latest version (possibly not required, for safety)
- docker tag britboy4321/e0testingapp:prod registry.heroku.com/e0testingapp/web  # Tag it ready for Heroku
- docker login --username=drawlinson48@gmail.com --password=$Heroku_finalpass2 registry.heroku.com
- docker push registry.heroku.com/e0testingapp/web   # put it onto Heroku

- echo "CONTINUOUS DEPLOYMENT SETUP COMPLETED"
- echo "-------------------------------------"
- echo "STARTING ACTUAL DEPLOY and RELEASE"
- echo "----------------------------------"

deploy:
  provider: script
  script: 
    heroku container:release web --app todoappbritboy
  on: 
    branch:
    - master
    - module15
    - Module15
    - masterbranch 
    - Phase 2
    - E0TestingApp