# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - e0testingapp

on:
  push:
    branches:
      - masterbranch
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_eac61e60de8a4b46a430872a89cde156 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f61184b3be5c4ff789b4abb92d93b2b9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_eac61e60de8a4b46a430872a89cde156 }}/britboy4321/e0testingapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'e0testingapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_50315c78600049e8b99c9c4f3e332dde }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_eac61e60de8a4b46a430872a89cde156 }}/britboy4321/e0testingapp:${{ github.sha }}'